### ISSUE TITLE
hd reload?

### ISSUE THREAD

**Issue by geminimiche** [randombyte-developer/holograms#11]
Can we get a /hd reload do you think?

thanks!

**Comment by randombyte-developer** [comment]
What should it do and what does 'hd' stand for?

**Comment by geminimiche** [comment]
when the input file is changed, to update the signs to the changes. currently i have to reload sponge entirely to avoid restarting to allow changes to take effect. HD is just a shortcut for hologram display; it doesn't matter what you call it, really,

**Comment by randombyte-developer** [comment]
You set the text of a hologram from the input file by listing the holograms and then clicking `[TFF]`. You don't have to reload anything. https://ore.spongepowered.org/RandomByte/Holograms/pages/Common%20workflow

**Comment by randombyte-developer** [comment]
Are you okay with that?

**Comment by geminimiche** [comment]
For my purposes, i'm not sure. maybe im just retarded, but i want a multi-line sign for our server rules. It seems i have to make like 13 signs, all one over the last, then map the lines to the input file then edit the input file so each line reads as i like it, then reload everything. Until i at least make the first sign the input file is blank and there's no indication of structure or what sign goes to what line in that file (the last version the input file order and the sign order/numbers were not congruent). I just want to do it all at once. Am I using your program wrong or missing a step?

**Comment by randombyte-developer** [comment]
You can only set the text of one single hologram(one line in a multiline hologram) from the text file or from ingame chat. 
Creating a multiline line hologram by putting several lines of text in the input file is not implemented yet. This is already planned for the next version, others have it suggested too.
