### ISSUE TITLE
Holograms disappear on server restart

### ISSUE THREAD

**Issue by Yorkforce** [randombyte-developer/holograms#12]
Not sure if this is a SpongeVanilla bug but recently we started noticing that all holograms disappear completely on a server restart.

Using SpongeVanilla 383 (Latest) with holograms 2.2
(also tested with SpongeVanilla 373, same problem)

No apparent error in the console or logs, they just cease to exist

**Comment by Brend-Smits** [comment]
Same issue happened to me on SpongeForge on an ealier version, not sure how it happened

**Comment by randombyte-developer** [comment]
This issue was reported by many users. It is Husky Crates which is causing the disappearing. I'm not sure if an update with a fix is available.

**Comment by Brend-Smits** [comment]
We do not have that plugin installed

**Comment by randombyte-developer** [comment]
There is simply no Minecraft related code in the reload code. It just generates the input.txt if it isn't there. It must be another plugin. Could you please test on a fresh server with only this plugin installed?

**Comment by Yorkforce** [comment]
Turns out this was caused by Grief Prevention flag entity-spawn set to false, obvious really.

Sorry about that!

**Comment by Yorkforce** [comment]
Or not, they disappeared again.
