### ISSUE TITLE
Unable To Create Holograms

### ISSUE THREAD

**Issue by SjsolisZXA** [randombyte-developer/holograms#13]
**Sponge Forge:** spongeforge-1.11.2-2282-7.0.0-BETA-2302
**Holograms:** 2.2

When I executed the command `/holograms create TESTHOLOGRAM`, I received the error: `Error occured while executing commnad: A DataManipulatorBuilder is not registered for the manipulator class: de.randombyte.holograms.data.HologramData`

**Comment by randombyte-developer** [comment]
Are there any errors at server startup?

**Comment by randombyte-developer** [comment]
https://forums.spongepowered.org/t/holograms-easily-create-floating-texts/12861/247?u=randombyte

**Comment by randombyte-developer** [comment]
Try v2.3, which is for Sponge API v7.
