### ISSUE TITLE
Unknown Plugin registering custom data!   

### ISSUE THREAD

**Issue by SjsolisZXA** [randombyte-developer/holograms#14]
Sponge Forge Version: spongeforge-1.11.2-2282-6.0.0-BETA-2297
Holograms Version: holograms-2.2

`> /*******************************************************************************************************************************/
/* Unknown Plugin registering custom data!                                                                                     */
/*******************************************************************************************************************************/
/* Sponge's Custom Data system must know what plugin container is registeringwhat                                              */
/* custom data to assign a "legacy" id for the custom data! It is notrecommended                                               */
/* for developers to continue using the old registration methodsas they will be                                                */
/* removed in future API versions! Please notify the developerof the offending                                                 */
/* plugin to update!                                                                                                           */
/* Since the plugin id cannot be determined, custom data will not be registered!                                               */
/* The following custom data was attempted                                                                                     */
/* DataManipulator : de.randombyte.holograms.data.HologramData                                                                 */
/* ImmutableManipulator : de.randombyte.holograms.data.HologramData$Immutable                                                  */
/* ManipulatorBuilder : de.randombyte.holograms.data.HologramData$Builder                                                      */
/* java.lang.Exception: null                                                                                                   */
/*     org.spongepowered.common.data.SpongeDataManager.register(SpongeDataManager.java:231)                                    */
/*     de.randombyte.holograms.Holograms.onPreInit(Holograms.kt:47)                                                            */
/*     org.spongepowered.common.event.listener.GamePreInitializationEventListener_Holograms_onPreInit22.handle(Unknown Source) */
/*     org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)                                    */
/*     org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314)                                  */
/*     org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345)                                  */
/*     org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:212)                                                        */
/*     sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                             */
/*     sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)                                                             */
/*     sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)                                                         */
/*     java.lang.reflect.Method.invoke(Unknown Source)                                                                         */
/*     com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)                                         */
/*     com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)                 */
/*     com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)                                                         */
/*     com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)                                             */
/*     com.google.common.eventbus.EventBus.post(EventBus.java:275)                                                             */
/*     net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)                           */
/*     net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)                             */
/*     sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                             */
/*     sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)                                                             */
/*     sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)                                                         */
/*     java.lang.reflect.Method.invoke(Unknown Source)                                                                         */
/*     com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)                                         */
/*     com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)                 */
/*     com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)                                                         */
/*     com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)                                             */
/*     com.google.common.eventbus.EventBus.post(EventBus.java:275)                                                             */
/*     net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:553)                            */
/*     net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)                            */
/*     net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)                                                 */
/*     net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:100)                            */
/*     net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)                                 */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)                                   */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)                                                      */
/*     java.lang.Thread.run(Unknown Source)                                                                                    */
/*******************************************************************************************************************************/`

**Comment by randombyte-developer** [comment]
This is a known issue. Sponge's data registration changed with api 6. To avoid this problem use a sponge build against api < 6 until an update is released.

**Comment by randombyte-developer** [comment]
This is a known issue. Sponge's data registration changed with api 6. To avoid this problem use a sponge build against api < 6 until an update is released.

**Comment by randombyte-developer** [comment]
@SjsolisZXA https://forums.spongepowered.org/t/holograms-easily-create-floating-texts/12861/247?u=randombyte

**Comment by randombyte-developer** [comment]
Try v2.3, which is for Sponge API v7.
