### ISSUE TITLE
java.lang.NoClassDefFoundError: de/randombyte/holograms/shaded/kosp/bstats/BStats

### ISSUE THREAD

**Issue by EmanYm** [randombyte-developer/holograms#15]
What did I do wrong?
https://hastebin.com/bosobojeho.pl

SpongeVanilla 5.2.0-Beta 385
Holograms 2.2

**Comment by randombyte-developer** [comment]
Try redownloading the plugin. A file in the plugin wasn't found.

**Comment by EmanYm** [comment]
That was it.  Just a corrupt download.
