### ISSUE TITLE
"Could not pass GamePreInitializationEvent$Impl"

### ISSUE THREAD

**Issue by EmanYm** [randombyte-developer/holograms#19]
[This](https://pastebin.com/ARdAFmFT) appears in the console during startup.

Running on a `SpongeVanilla version 1.12.1-7.0.0-BETA-315` server

**Comment by randombyte-developer** [comment]
Api v7 is currently not supported, keeping this issue to motivate me to do an update.

**Comment by EmanYm** [comment]
Right on.  Love the prompt response.  Thanks RB

**Comment by BrainStone** [comment]
I could use an update too.

**Comment by randombyte-developer** [comment]
I just saw that API v7 isn't even released yet. Why would you need the server to run API v7?

**Comment by BrainStone** [comment]
@randombyte-developer 1.12.x is only available on API 7

**Comment by randombyte-developer** [comment]
Try v2.3, which is for Sponge API v7.
