### ISSUE TITLE
Plans to support API 7 MC 1.12

### ISSUE THREAD

**Issue by Brend-Smits** [randombyte-developer/holograms#22]
Heey! 
I was wondering if you have any plans on supporting SpongeAPI 7 and MC 1.12? 
It had a major Cause refactor meaning the plugin will probably error with current state.

**Comment by randombyte-developer** [comment]
Yes, I should do that. But this plugin is far from top priority on my list. You may create a PR to update the plugin ;)

**Comment by randombyte-developer** [comment]
Try v2.3, which is for Sponge API v7.
