### ISSUE TITLE
"A DataManipulatorBuilder is not registered"

### ISSUE THREAD

**Issue by EmanYm** [randombyte-developer/holograms#23]
[The issue](https://github.com/randombyte-developer/holograms/issues/13) still persists in Sponge Vanilla 1.11.2-beta 258
I have a feeling it was fixed in a newer version, but they are API7.  I'm not sure if API6 plugins will work for on an API7 environment.  I highly doubt Sponge would push a fix for such an old version of the API.

[relevant log fragments](https://hastebin.com/asugezufob.md)

**Comment by randombyte-developer** [comment]
Related to https://github.com/SpongePowered/SpongeCommon/issues/1396, @gabizou once said he had a fix locally but sadly forgot to push it.

**Comment by EmanYm** [comment]
Do you know if there is a chance the fix will be pushed to the API 6 branch?  Or have they all but abandoned that branch for API7?

**Comment by randombyte-developer** [comment]
I really don't know.

**Comment by randombyte-developer** [comment]
Try v2.3, which is for Sponge API v7.
