### ISSUE TITLE
'HologramsService' not available

### ISSUE THREAD

**Issue by zachdoug24** [randombyte-developer/holograms#25]
Whenever I attempt to create a Hologram, I receive the `Error occurred while executing command: 'HologramsService' not available!` What's the reasoning for this? These are all of the mods in `/mods/` of my server. 

![](https://i.imgur.com/RxRfd3m.png)

**Comment by randombyte-developer** [comment]
Please upload the whole server log to [gist.github.com](https://gist.github.com).

**Comment by randombyte-developer** [comment]
Closed due to inactivity.
