### ISSUE TITLE
Could not initialise class de.randombyte.holograms.data.HologramKeys

### ISSUE THREAD

**Issue by tolly765** [randombyte-developer/holograms#27]
Whenever the /holograms command is invoked (no matter what the extra parameters are), I get this error message: https://gist.github.com/tolly7654/4dfa1f01d0c30f9733c216210bcb8a21
The wierd thing though, is that holograms that were placed before this error occurred still show up - http://prntscr.com/hwdsaf

I am running the Revelations modpack with SpongeForge 1.12.2-2555-7.1.0-BETA-2815 and the latest version of Holograms as of this post (2.3). Any help would be appreciated!

**Comment by randombyte-developer** [comment]
This is a known bug. Once a another bug in sponge is fixed, I'll update this plugin. The existing holograms really only are normal armor stands.

**Comment by tolly765** [comment]
Awesome news. Any workaround for now? Or will we just have to wait? 😛

**Comment by randombyte-developer** [comment]
Use a sponge version from around 31.12.17.

**Comment by tolly765** [comment]
No thanks, I'll just hang fire for for it then. Thanks for the update though randombyte ❤️

**Comment by randombyte-developer** [comment]
Please try https://github.com/randombyte-developer/holograms/releases/tag/v3.0 and the latest sponge version.
