### ISSUE TITLE
I can't place or do anything with holograms?

### ISSUE THREAD

**Issue by FuelPhantom** [randombyte-developer/holograms#28]
Every time it gives me the same error and I've set the perms twice to make sure I've done it correct. I have no clue what's wrong or what to do to get it working...
![image](https://user-images.githubusercontent.com/36657933/36412449-413a3cd6-1612-11e8-8601-3dd4f4c2920f.png)

**Comment by R-Josef** [comment]
same problem, i can't do anything too!

**Comment by FuelPhantom** [comment]
Hmm hopefully we can get it sorted because it's the only sponge hologram plugin I can find and I really need to use it for a server :crying_cat_face:

**Comment by randombyte-developer** [comment]
What's your sponge, minecraft and holograms plugin version? And please send the whole server log.

**Comment by FuelPhantom** [comment]
Minecraft - 1.10.2, Holograms - 3.1 and spongeforge-1.10.2-2477-5.2.0-BETA-2793.

I'm just loading up Minecraft because I made some server changes, if it still doesn't work I'll send a screenshot of the log.

**Comment by FuelPhantom** [comment]
Here's what it says in console:

![image](https://user-images.githubusercontent.com/36657933/36437172-2f04e4b6-165e-11e8-8e57-3937b1fb75c7.png)
![image](https://user-images.githubusercontent.com/36657933/36437212-47f60d4c-165e-11e8-92ac-8306f6bd5da6.png)

(I had to edit the screenshots because I didn't see that stupidly long line that got cut off).

**Comment by FuelPhantom** [comment]
Maybe I should try getting an older version of the mod? That's the only thing I can personally think of doing.

**Comment by FuelPhantom** [comment]
Don't matter I was just being dumb because I had the wrong version. Somehow I managed to download the wrong one -_-

**Comment by randombyte-developer** [comment]
Ok.

For future reference: https://ore.spongepowered.org/RandomByte/Holograms/versions

![bildschirmfoto vom 2018-02-21 19 56 50](https://user-images.githubusercontent.com/10366256/36499416-731c5c22-1741-11e8-936f-cdbe828c5e03.png)
The Sponge version which is compatible is shown.
