### ISSUE TITLE
PlaceholderAPI

### ISSUE THREAD

**Issue by Vizis** [randombyte-developer/holograms#29]
Are you going to add placeholderAPI support?

**Comment by randombyte-developer** [comment]
This plugin would have to work with native Minecraft code(NMS packets) to achieve this. This is a lot of work I can't afford right now. I'm rather looking forward to Sponge implementing ['contextual data'](https://github.com/SpongePowered/SpongeAPI/pull/1046) which allows me to easily accomplish your request.
