### ISSUE TITLE
Space added to end of bold holos

### ISSUE THREAD

**Issue by Shmeeb** [randombyte-developer/holograms#30]
It seems that when holograms are started with bold text, the end has extra blank space added to it. &r at the end does not fix it either. Additionally longer hologram text seems to add more blank characters

https://i.gyazo.com/b721d7407ef3630a11e4dbf4c6e7aefb.png

**Comment by randombyte-developer** [comment]
Hm, ok. Thanks for reporting. Will look into it.

Do you create the holograms by hand or is it a plugin?

**Comment by randombyte-developer** [comment]
Try this: https://github.com/randombyte-developer/holograms/releases/tag/v3.1.5

**Comment by Shmeeb** [comment]
fixed
