### ISSUE TITLE
Crashes On API6

### ISSUE THREAD

**Issue by GershonR** [randombyte-developer/holograms#4]
http://pastebin.com/AyzCkFKD

**Comment by randombyte-developer** [comment]
As always, please provide all necessary information: sponge version, sponge implementation, plugin version(look at file name), how to reproduce the crash. 
Also please first try a fresh setup server with only this plugin. 
Ps: also please post the full server log from startup.

**Comment by GershonR** [comment]
On clean server with only this, it lists the Sponge and Forge:
http://pastebin.com/4yP5AeFj

**Comment by randombyte-developer** [comment]
Hm, no idea. Could you please post the full server log, not only the crash log?

**Comment by GershonR** [comment]
http://pastebin.com/y3HHETcH

**Comment by randombyte-developer** [comment]
You are using the backported version of my plugin, please use the normal v1.1.3. See https://github.com/randombyte-developer/holograms/issues/5

**Comment by randombyte-developer** [comment]
Closing because of no feedback.
