### ISSUE TITLE
No config {Console error}

### ISSUE THREAD

**Issue by Fadirstave** [randombyte-developer/holograms#5]
When i run a test command to setup a hologram. I recive the following issues.

1. This is spammed in console and in chat: http://paste.feed-the-beast.com/view/7a0e3b98
2. The hologram does not place
3. No config file

**Comment by randombyte-developer** [comment]
Are you sure you are using the latest version and not the backport? What is the plugin file name?

**Comment by Fadirstave** [comment]
Im using the latest as of today 11/28/16 
PL - holograms-v1.1.3-for-api-v4.1.0.jar 
If there is a newer version I am not seeing it.

**Comment by randombyte-developer** [comment]
That's the backport, you are probably on api 5. Use the normal v1.1.3. Sorry for the inconvenience. 
Also something to note, you might run into this problem: https://forums.spongepowered.org/t/holograms-easily-create-floating-texts/12861/113?u=randombyte Just use an old enough sponge build. This crash is related to https://github.com/zml2008/configurate/issues/58

**Comment by Fadirstave** [comment]
Okay. Sadly I am running large modpacks which cannot be ran with an older version.
Will be waiting for an update.

-Thanks!

**Comment by randombyte-developer** [comment]
I will change the config structure if Configurate doesn't get updated soon.
