### ISSUE TITLE
Suggestion: create multi-holograms in-game

### ISSUE THREAD

**Issue by Eufranio** [randombyte-developer/holograms#7]
The command would be **/holograms cml <number of lines> <text of each line, separated by %>**

Example: **/holograms cml 2 &c&lJoin our server now!%&bwww.myserver.com.br** or **/holograms cml 2 &c&lJoin our server now! % &bwww.myserver.com.br**

**Comment by randombyte-developer** [comment]
That is to some extent not doable because the minecraft chat does only allow 100 character long commands. You can use the config for multiline holograms.

**Comment by Eufranio** [comment]
You would just add it, not replace the actual way of creating holograms. Then, who want a quick and small hologram can do it.

**Comment by randombyte-developer** [comment]
Ok, good idea!

**Comment by randombyte-developer** [comment]
Added in 54c4c188b8a2c3c3e4192cb1b8394d1f16897843.
