### ISSUE TITLE
Not Deleting Hologram

### ISSUE THREAD

**Issue by Shane1199** [randombyte-developer/holograms#8]
I made the mistake of removing the multiline hologram from the config rather than through the command. It didn't regenerate in the config, and I'm left with the hologram still there. Can there be a check made in the plugin to kill a hologram if it's missing in the config? And also, how do I remove the free-standing one? I think there is a remove nearest entity command in vanilla.

**Comment by randombyte-developer** [comment]
Automatic deleting doesn't work. The plugin can't just remove all ArmorStands that aren't in the config. Maybe someone built his own ArmorStand with armor on. That can't just be destroyed.
